title: Core Coin
email: contact@corecoin.cc
description: >- # this means to ignore newlines until "baseurl:"
  The Value Custodian for a Decentralised World
baseurl: "" # the subpath of your site, e.g. /blog
donate:
  xce:

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
