title: Core Coin
email: contact@corecoin.cc
description: >-
  The Value Custodian for a Decentralised World
baseurl: ""
donate:
  xce:

markdown: kramdown
theme: minima
timezone: UTC
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

include:
  - node_modules/@cryptohub/coco/dist/sass
